language: python
dist: trusty
addons:
  postgresql: '9.6'
services:
  - postgresql
python:
  - '3.5'
  - '3.6'
install: 'pip install -r test/requirements.txt'
script:
  - py.test --cov-report xml --cov .
  - flake8
  - isort --check-only --recursive
after_success:
  - python-codacy-coverage -r coverage.xml
