language: python
services:
  - postgresql
before_script:
  - psql -c 'create database slogan-test;' -U postgres
python:
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
install: "pip install -r test/requirements.txt"
script: py.test
